"""
Drift Severity — Decision Layer

Consumes diagnostic drift reports generated by data_drift.py
and converts them into severity levels using PSI thresholds.

- This file does NOT compute drift
- It only interprets drift metrics
"""

import json
from pathlib import Path

# Importing drift storage function
from store_drift_metrics import store_drift_metric


# Paths
DRIFT_REPORT_DIR = Path("monitoring/drift_reports")

# PSI thresholds (industry-aligned)
LOW_THRESHOLD = 0.1
MEDIUM_THRESHOLD = 0.25


def classify_drift(psi_score: float) -> str:
    """
    Convert PSI score into severity label.
    """
    if psi_score < LOW_THRESHOLD:
        return "LOW"
    elif psi_score < MEDIUM_THRESHOLD:
        return "MEDIUM"
    else:
        return "HIGH"


def main():
    for report_file in sorted(DRIFT_REPORT_DIR.glob("production_batch_*_drift.json")):
        batch_name = report_file.stem.replace("_drift", "")

        with open(report_file) as f:
            drift_report = json.load(f)

        for feature, metrics in drift_report.items():
            # Skip malformed entries defensively
            if "psi" not in metrics:
                continue

            psi_score = metrics["psi"]
            drift_level = classify_drift(psi_score)

            store_drift_metric(
                batch=batch_name,
                feature=feature,
                drift_score=psi_score,
                drift_level=drift_level,
            )

        print(f"Drift severity processed for {batch_name}")


if __name__ == "__main__":
    main()